version: "3.9"

services:
  backend:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./backend:/backend-bookstore-drf
      ports:
        - "8000:8000"
      depends_on:
        - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_user_/1
    volumes:
      - pgdata:/var/lib/posgresql/data
  web_migrations:
    build: .
    command: python manage.py migrate
    volumes:
      - ./backend:/backend-bookstore-drf
volumes:
  pgdata: