version: "3.9"

services:
  backend:
      build: ./backend
      command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./backend:/backend-bookstore-drf
      ports:
        - "8000:8000"
      depends_on:
        - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_user_/1
    volumes:
      - pgdata:/var/lib/posgresql/data
  # frontend:
  #    build: ./frontend
  #    container_name: frontend
  #    command: bash -c "npm start"
  #    ports:
  #     - '3000:3000'
  #    stdin_open: true
  #    tty: true
  #    environment:
  #     - WATCHPACK_POLLING=true
volumes:
  pgdata:
  